print("Welcome to Naomi's Madlibs!")
name=input("What is your name?  ")
print(f"Hello {name}! Today you are going to make a Mad Lib!")
celebrity=input("Pick a celebrity: ")
noun=input("Now pick a noun: ")
adjective=input("Now an adjective: ")
verb=input("Pick a verb: ")
noun2=input("Pick another noun: ")
pluralnoun=input("Now pick a plural noun: ")
print("Ok! Now that we have all of the words, let's read your Mad Lib!")
input("")
print(f"So today was the wedding of Taylor Swift and Travis Kelce, which started out normal until {celebrity} burst through the doors holding a {noun} and screaming something about destiny. Everyone froze. Taylor whispered, Why is {celebrity} here? Before security could do anything, {celebrity} climbed onto a table, looked directly at Travis, and started to {verb} aggressively while holding the {noun} like it was a microphone. Someone’s grandma yelled, THIS IS WHY WE CAN’T HAVE NICE THINGS! Meanwhile, a {adjective} {noun2} somehow rolled down the aisle and crashed into the cake table, launching {pluralnoun} everywhere. Travis just stood there like, Honestly… this feels on-brand. Taylor sighed, grabbed the mic, and said, Alright. Whoever brought the {noun} owes me a new album idea. And that’s how the wedding ended with security chasing {celebrity} through a pile of {pluralnoun} while the DJ played Love Story.")